# This workflow will build a golang project

name: Go CI/CD workflow
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
          version: latest
    - name: Lint
      run: golangci-lint run --timeout=5m
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
  tag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create new tag automatically
        id: version
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true